### ISSUE TITLE
Cannot read full CPU specs with 1366*768 screen

### ISSUE THREAD

**Issue by NetDin0** [AstraExt/astra-monitor#121]
![Captura desde 2024-04-28 23-38-58](https://github.com/AstraExt/astra-monitor/assets/43504858/beb1f398-34df-49af-8203-4c4c308854a8)
## Description

Cannot read full CPU specs with 1366*768 screen

## Steps to Reproduce

1. Just install with default ubuntu fonts, size, etc
2.
3. 

## Environment

-   **Astra Monitor Version**: 24(egov41)
-   **GNOME Version**: 46
-   **Operating System and Version**: ubuntu 24.04
-   **Other Relevant System Information**:

**Comment by ljuzig** [comment]
Thank you. I'm gonna try to fix this in the next version. There is also another bug in the parsing of the value (see `Socket(s)`).

**Comment by NetDin0** [comment]
> Thank you. I'm gonna try to fix this in the next version. There is also another bug in the parsing of the value (see `Socket(s)`).

What about the icon to launch the task manager? I have seen it in many images but it is not present in my extension. Am I missing something?

**Comment by ljuzig** [comment]
[This](https://github.com/AstraExt/astra-monitor/blob/618372c41147e5c8588ea854d4fe52fd7d51469f/src/menu.ts#L170) check is failing. `gnome-system-monitor.desktop` might be missing on your system or this may be caused by GNOME 46 since you're on Ubuntu 24.04. They updated the system monitor app to GTK4, I need to test that!
