### ISSUE TITLE
Gnome Session Version 42 Support 

### ISSUE THREAD

**Issue by p-sims** [AstraExt/astra-monitor#124]
## Description

POP!OS 22 LTS is currently running Gnome 42 rather than 45 or 46 that AstraExt currently supports. Is there are plans for support Gnome 42? Is supporting Gnome 42 a lot of work or is it just un-tested?

I'm in the process of moving from MacOS were I used iStat to linux so Astra looks very appealing tool.

Thanks,

**Comment by ljuzig** [comment]
I moved to Linux from MacOS about an year ago (after more than 15 years!) and felt the lack of iStat, that's why I created Astra Monitor.

Anyway, GNOME 45 introduced breaking changes, porting an extension to earlier versions would be very time consuming and would be equivalent to rewriting a large part of the extension. Pop!OS will soon release its new LTS version which, by the way, will no longer feature GNOME and therefore will most likely not support this extension. Almost all other distros are now releasing LTS versions with GNOME versions of 45 or later so I'm sorry but I don't think it's worth it.
