### ISSUE TITLE
Monitor indicator move slightly on workspace change when aligned to the left on the panel.

### ISSUE THREAD

**Issue by C-512L** [AstraExt/astra-monitor#137]
## Description

I think the issue title itself explains it well enough.

## Steps to Reproduce

1. Install the extension
2. Configure astra to align left on the panel
3. Switch between workspaces

## Screenshots
Technically not a screenshot but a video as it showcases the bug better.
[Screencast from 2024-07-27 16-07-42.webm](https://github.com/user-attachments/assets/2488f05d-2d93-4d2a-9c57-3e178d0fb161)

## Environment
-   **Astra Monitor Version**: 25 (EGOv42)
-   **GNOME Version**: 46
-   **Operating System and Version**: Fedora Workstation 40
-   **Other Relevant System Information**:

## Logs

As far as I have tested, the systemd journal doesn't have any records from astra, or at least not that can be related to this bug.

**Comment by lepa22** [comment]
Actually it's not the extension that moves. It's GNOME's workspace switcher that gets resized slightly (I'd say 1-2 px) when you switch workspaces. In the video below, I'm hovering my mouse over the workspace switcher so that it gets highlighted and you can see the resizing when the workspace is changed:

https://github.com/user-attachments/assets/fb5d68e4-796e-43c2-b4b5-3dbc110fb5cc

So this is not actually an Astra Monitor bug but a GNOME one.

**Comment by C-512L** [comment]
Thanks for noticing it, somehow I didn't notice this. I will probably file an issue on the GNOME issue tracker (if it doesn't have one already).
