### ISSUE TITLE
Customizing the order of indicators within the headers

### ISSUE THREAD

**Issue by lepa22** [AstraExt/astra-monitor#37]
## Description
The usage percentages are positioned to the right of the graphs for all items on the top bar except for the _Storage_ item. For reasons of uniformity the usage percentages should be all positioned to the same side, either to the right or to the left of the graphs of each item.

I think that the best position for the percentages would be right next to the respective icon, as it is for the _Sensors_ item which has no graph. This way even having graphs enabled for some items would result in a uniform appearance.

## Steps to Reproduce
1. Install and enable the extension.
2. Enable graphs and percentages for the items on the top bar.
3. For all items the percentages are positioned to the right of the graphs except for the _Storage_ item.

## Screenshots
![image](https://github.com/AstraExt/astra-monitor/assets/16370046/2093009b-0ee0-49ae-b09a-2427bdb0ba34)

## Environment
- **Astra Monitor Version**: 6 (EGOv8)
- **GNOME Version**: 45.3
- **Operating System and Version**: Fedora 39 Workstation

**Comment by ljuzig** [comment]
This is actually intended. The percentage in that case refers to the used space of the hard disk and thus is placed next to the hard disk occupation bar. The graphs, on the other hand, relate to IO speed. However, I plan in the future to add customization of the order of the indicators within the various headers, so I am tagging this as an enhancement rather than a bug.
