### ISSUE TITLE
Enhancement Request:  Control digits after decimal point length 

### ISSUE THREAD

**Issue by 3dsf** [AstraExt/astra-monitor#41]
## Description

Displaying a sensor temp can become distracting when it changes from an integer like display to a float like display and vice-versa.  eg// 46°C to 44.4°C

## Steps to Reproduce

1.  Enable display of a temp sensor

## Screenshots

![Screenshot from 2024-01-25 20-08-19](https://github.com/AstraExt/astra-monitor/assets/44537624/86eb4268-42b9-49ca-9d3a-3cd9c1085c88)
![Screenshot from 2024-01-25 20-10-44](https://github.com/AstraExt/astra-monitor/assets/44537624/12fb9a6c-c9b6-4655-94a0-92a5b3132141)

## Environment

- **Astra Monitor Version**: [preV8](https://github.com/AstraExt/astra-monitor/issues/38#issuecomment-1908998274)
- **GNOME Version**: 46
- **Operating System and Version**: Fedora Rawhide (6.8)
- **Other Relevant System Information**:

**Comment by ljuzig** [comment]
Well, actually we have the settings for the Maximum Number of Figures on almost all values, but not on sensors. The reason is pretty simple: for high integer values like 2500 RPM, we cannot convert them to a decimal format, such as 2.5k. Currently, we try to detect if it's an integer value; otherwise, we format it as a floating-point number. I'm going to add an option to always convert a value to a floating-point format and allow selection of the number of digits to display. This option will be disabled by default.

**Comment by ljuzig** [comment]
Done. This will be available in v9.

![image](https://github.com/AstraExt/astra-monitor/assets/11982322/adca8686-48c9-47e4-82e4-bc059bd42dc7)
