### ISSUE TITLE
Enhancement: Add transparency to graphs so that it is more clear if they are stacked or layered

### ISSUE THREAD

**Issue by lepa22** [AstraExt/astra-monitor#58]
## Description

Have a look at this graph:

![image](https://github.com/AstraExt/astra-monitor/assets/16370046/89dbbbd4-34d2-4588-9c79-01d28535f81c)

It is not clear if the red graph is above the blue graph (stacked) or if the red graph is behind the blue graph (layered). I think that adding transparency to the graphs will help better understand what's going on. However, since just adding transparency will still look like a solid color and the same issue might still not get completely resolved, I also propose that the top part of the red and blue graphs uses an opaque solid line.

For reference, I mean something like this:

![image](https://github.com/AstraExt/astra-monitor/assets/16370046/58fb0f07-ac07-4c46-9523-0d38b1cb07c1)
<sup>Image from https://stackoverflow.com/a/47645844)</sup>

PS: The same applies for the bars, although the ones in the top bar are quite small, so I am not sure how it would look in that case.

**Comment by ljuzig** [comment]
Adding too many elements to graphs could have a big impact on performance, especially for graphs that are always visible on the top bar. However, I have plans to add some customization elements to the charts, currently even the colors are not changeable and when I'm going to get my hands on the customization of the graphs I will add other options for personalization in addition to the colors, but I think that the default version will stay this one because it is the one that performs best and is the lightest.

**Comment by lepa22** [comment]
Ok, it's understandable if adding transparency would affect performance.

**Comment by ljuzig** [comment]
You will be able to add transparency to the color once color customization will be added.
