### ISSUE TITLE
Memory is reported in GBs, whereas it should in GiBs

### ISSUE THREAD

**Issue by fedkad** [AstraExt/astra-monitor#67]
## Description
I noticed that, in the new version, the various amounts of memory are reported in GBs (1000³).

This may be acceptable for Storage and Network, but for Memory I expect them to be in GiBs (1024³) and it was so in the previous versions.

There is currently no option in **Memory** _Settings_ to switch between GB and GiB, i.e., something similar to **Data Unit** setting in **Storage** or **Network**.

## Screenshots
![image](https://github.com/AstraExt/astra-monitor/assets/113997707/02cdf56d-3f2a-4401-a7e8-a83ef86bee44)

My hardware has 24 GiBs of RAM, but it is reported 25 GB.

## Environment

- **Astra Monitor Version**: 12
- **GNOME Version**: 45.2
- **Operating System and Version**: Ubuntu 23.10
- **Other Relevant System Information**: NA

**Comment by ljuzig** [comment]
Yeah, I noticed that. In the latest version I fixed some conversions but it turns out that linux provide data in a very confusing way:

[While the file shows kilobytes (kB; 1 kB equals 1000 B), it is actually kibibytes (KiB; 1 KiB equals 1024 B). This imprecision in /proc/meminfo is known, but is not corrected due to legacy concerns - programs rely on /proc/meminfo to specify size with the "kB" string. ](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/deployment_guide/s2-proc-meminfo)

I'm gonna add also unit preferences for Memory, defaulting to KiB format.
