### ISSUE TITLE
Icone Name option does not seem to do anything.

### ISSUE THREAD

**Issue by SinghaniaV** [AstraExt/astra-monitor#87]
## Description

What is the Icon Name option supposed to do? 
Can we set custom icons?
Can we replace icons with text?

## Screenshots

![image](https://github.com/AstraExt/astra-monitor/assets/75255173/4bf7fff1-b673-4ee2-a8aa-b22b2fe0880c)

## Environment

- **Astra Monitor Version**: 15
- **GNOME Version**: 45
- **Operating System and Version**: Arch Linux

**Comment by ljuzig** [comment]
This uses icons pack you have installed on your system. `cpu-symbolic` may not work for you because you have no theme with `cpu-symbolic` icon. If you install ie [Kora](https://github.com/bikass/kora) you will get [Kora's `cpu-symbolic`](https://github.com/bikass/kora/blob/3ca0a4e27826f6aa186357246a3ed8749f38ed01/kora/devices/symbolic/cpu-symbolic.svg#L4).
